security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'
    providers:
        app_user_provider:
            entity:
                class: App\User\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
                default_target_path: main
            two_factor:
                auth_form_path: two_factor_login
                check_path: 2fa_login_check
            logout:
                path: logout
                target: login

    access_control:
        - { route: login, roles: PUBLIC_ACCESS }
        - { route: register, roles: PUBLIC_ACCESS }
        - { route: two_factor_login, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { route: disable, roles: ROLE_USER }
        - { route: enable, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
        firewalls:
            main:
                form_login:
                    enable_csrf: false
