controllers:
    resource: '../src/**/{*Action.php}'
    type: attribute
    
2fa_login_check:
    path: /2fa_check
app_redirect_root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: false
